[package]
name = "picotest"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Test framework for Picodata plugin"
homepage = "https://picodata.io/"
repository = "https://github.com/picodata/picotest"
documentation = "https://github.com/picodata/picotest"
keywords = ["picodata", "test"]
categories = ["development-tools::testing"]
readme = "README.md"
authors = [
    "Alexandr Sorokin <a.sorokin@picodata.io>",
    "Boris Sinyapkin <b.sinyapkin@picodata.io>",
    "Evgeniy Mitin <e.mitin@picodata.io>"
]


[dependencies]
picotest_macros = { path = "../picotest_macros", version = "0.1.0" }
picotest_helpers = { path = "../picotest_helpers", version = "0.1.0" }
anyhow = "1.0.97"


[dev-dependencies]
uuid = { version = "1.16.0", features = ["v4"] }
rstest = "0.25.0"
constcat = "0.5.1"
serde_yaml = "0.9.34"
