name: Release

on:
  release:
    types: [released]

jobs:
  release-crate:
    name: release crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85"
          components: clippy, rustfmt

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Publish crates
        run: cargo workspaces publish --from-git --yes
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
